#TODO-1 application.properties 의 상수들을 application.yml 에 추가한다.
#TODO-2 application-dev.yml application-prod.yml 을 생성한다.
#TODO-3 각각 profile 로 실행한다.
#TODO-3 application.properties, application-dev.properties, application-prod.properties 파일을 삭제한다.

